// src/components/ChatMessage.vue
<script setup>
import { onMounted, ref } from "vue";
import DOMPurify from 'dompurify'
import emojiRegex from "emoji-regex";

const props = defineProps({
  time: String,
  badges: Array,
  username: String,
  text: String,
  color: String,
  emotes: String,
  highlight: Boolean
});

const isVisible = ref(true);
const sanitizedText = ref('')
const $element = ref(null)

function parseEmotes() {
  if (!props.emotes) return props.text;

  const emoteData = props.emotes.split("/").map((emote) => {
    let emoteList = [];
    const emoteSplit = emote.split(":");

    const src = emoteSplit[0];
    const placesString = emoteSplit[1];

    placesString.split(",").map((place) => {
      const placeSplit = place.split("-").map(Number);
      emoteList.push({
        src: src,
        start: placeSplit[0],
        end: placeSplit[1],
      });
    });

    return emoteList;
  });
  const unpackRecurciveLists = (arr) =>
    arr.reduce(
      (acc, val) =>
        acc.concat(Array.isArray(val) ? unpackRecurciveLists(val) : val),
      []
    );

  let emotes = unpackRecurciveLists(emoteData);
  emotes.sort((a, b) => a.start - b.start);
  emotes.reverse();


  let formattedMessage = props.text;
  let emoteIteration = 0;
  emotes.forEach(({ src, start, end }) => {
    formattedMessage =
      formattedMessage.slice(0, start) +
      `<img src="https://static-cdn.jtvnw.net/emoticons/v2/${src}/default/dark/1.0" class="smile" style="animation-delay: 0.${emoteIteration}s">` +
      formattedMessage.slice(end + 1);

    emoteIteration++;
  });

  return formattedMessage;
}

function sanitizeText(text) {
  return DOMPurify.sanitize(text, {
    ALLOWED_TAGS:  ["img"],
    ALLOWED_ATTR: ["src", "class", "style", "alt"],
  });
}
function setAppleEmojs(text) {
  const regex = emojiRegex();
  return text.replace(regex, (emoji) => {
    const encodedEmoji = encodeURIComponent(emoji);
    return `<img 
             src="https://emojicdn.elk.sh/${encodedEmoji}?style=apple" 
             class="apple-emoji" 
             alt="${emoji}"
           >`;
  });
}

onMounted(() => {
  sanitizedText.value = sanitizeText(setAppleEmojs(parseEmotes()))

  setTimeout(
    () => {
      $element.value?.classList.add('messageOut')
    },
    14 * 1000
  )
  setTimeout(
    () => {
      isVisible.value = false
    },
    15 * 1000
  )
});
</script>

<template>
  <div class="chatMessage" v-if="isVisible" ref="$element">
    <span>
      <span class="messageTime">{{ time }}</span>
      <span class="userBadges">
        <img
          v-for="badge in badges"
          class="badge"
          :src="badge"
        />
      </span>
      <span class="messageUsername" :style="'color: ' + color">{{
        username
      }}</span
      ><span class="spliter">: </span>
      <span :class="highlight ? 'highlighted messageText' : 'messageText'" v-html="sanitizedText"></span>
    </span>
  </div>
</template>

<style>
.highlighted {
  background-color: #ffffff; 
  color: #000000 !important;
  padding: 0 10px;
}
@keyframes messageIn {
  0% {
    opacity: 0;
    transform: translateY(20px);
  }
  100% {
    opacity: 1;
    transform: translateY(0px);
  }
}
@keyframes messageOut {
  0% {
    opacity: 1;
    transform: translateY(0px);
  }
  99% {
    opacity: 0;
    transform: translateY(0px);
  }
  100% {
    opacity: 0;
    display: none;
    transform: translateY(0px);
  }
}
@keyframes message {
  0% {
    opacity: 0;
    transform: translateY(20px);
  }
  10% {
    opacity: 1;
    transform: translateY(0px);
  }
  90% {
    opacity: 1;
    transform: translateY(0px);
  }
  99% {
    opacity: 0;
    transform: translateY(0px);
  }
  100% {
    display: none;
    opacity: 0;
    transform: translateY(0px);
  }
}
@keyframes smile {
  0% {
    transform: scale(0%);
  }
  100% {
    transform: scale(100%);
  }
}
.chatMessage {
  transform: translateY(10px);
  animation: messageIn 0.3s forwards cubic-bezier(0.16, 0.24, 0, 1);
  position: relative;
  background-color: rgba(0, 0, 0, 0.5);
  border-radius: 10px;
  padding: 20px 24px;
  padding-top: 12px !important;
}
.chatMessage > span {
  display: block;
}
.messageOut {
  animation: messageOut 0.25s forwards cubic-bezier(0.57, 0.03, 0, 1);
}
.messageUsername {
  font-size: 26px;
  font-weight: 700;
  color: #fafafa;
}
.spliter {
  margin-left: 2px;
  font-size: 24px;
  color: #fafafa;
}
.messageText {
  font-size: 26px;
  font-weight: 400;

  width: 100%;
  overflow-x: hidden;

  overflow-wrap: break-word;
  word-break: break-word;
  color: #EFEFF1;
}
.messageTime {
  font-size: 26px;
  font-weight: 400;
  color: #adadb8;
  margin-right: 10px;
}
.badge {
  padding-right: 8px;
  width: 34px;
  position: relative;
  top: 8px;
  max-height: 34px;
}
.smile {
  transform: scale(0%);
  width: 34px;
  position: relative;
  top: 8px;

  animation: smile 0.3s forwards cubic-bezier(0.16, 0.24, 0, 1);
}
.apple-emoji {
  width: 34px;
  top: 8px;
  position: relative;
}
.message_reply {
  display: flex;
  flex-direction: row;
}
</style>

// packages/app/react/src/components/chat/message/ChatMessage.tsx
import './ChatMessage.css'

import { useEffect, useState } from "react";
import DOMPurify from "dompurify";
import emojiRegex from "emoji-regex";

interface ChatMessageProps {
  time: string;
  badges: string[];
  username: string;
  text: string;
  color: string;
  emotes?: string;
  highlight?: boolean;
}

export function ChatMessage({
  time,
  badges,
  username,
  text,
  color,
  emotes,
  highlight = false,
}: ChatMessageProps) {
  const [isVisible, setIsVisible] = useState(true);
  const [sanitizedText, setSanitizedText] = useState("");
  const [messageClass, setMessageClass] = useState("chatMessage");

  // --- парсер смайлов и эмодзи ---
  const parseEmotes = (): string => {
    if (!emotes) return text;

    const emoteData = emotes.split("/").map((emote) => {
      const emoteList: { src: string; start: number; end: number }[] = [];
      const [src, placesString] = emote.split(":");
      placesString.split(",").forEach((place) => {
        const [start, end] = place.split("-").map(Number);
        emoteList.push({ src, start, end });
      });
      return emoteList;
    });

    const flatten = (arr: any[]): any[] =>
      arr.reduce((acc, val) => acc.concat(Array.isArray(val) ? flatten(val) : val), []);

    const allEmotes = flatten(emoteData).sort((a, b) => a.start - b.start).reverse();

    let formattedMessage = text;
    allEmotes.forEach(({ src, start, end }, i) => {
      formattedMessage =
        formattedMessage.slice(0, start) +
        `<img src="https://static-cdn.jtvnw.net/emoticons/v2/${src}/default/dark/1.0" class="smile" style="animation-delay: 0.${i}s"/>` +
        formattedMessage.slice(end + 1);
    });

    return formattedMessage;
  };

  const sanitizeText = (raw: string): string =>
    DOMPurify.sanitize(raw, {
      ALLOWED_TAGS: ["img"],
      ALLOWED_ATTR: ["src", "class", "style", "alt"],
    });

  const setAppleEmojis = (input: string) => {
    const regex = emojiRegex();
    return input.replace(regex, (emoji) => {
      const encoded = encodeURIComponent(emoji);
      return `<img 
                src="https://emojicdn.elk.sh/${encoded}?style=apple"
                class="apple-emoji"
                alt="${emoji}"
              />`;
    });
  };

  useEffect(() => {
    const parsed = parseEmotes();
    const withEmojis = setAppleEmojis(parsed);
    setSanitizedText(sanitizeText(withEmojis));

    const outTimer = setTimeout(() => setMessageClass("chatMessage messageOut"), 14000);
    const hideTimer = setTimeout(() => setIsVisible(false), 15000);

    return () => {
      clearTimeout(outTimer);
      clearTimeout(hideTimer);
    };
  }, [text, emotes]);

  if (!isVisible) return null;

  return (
    <div className={`${messageClass} ${highlight ? "highlighted" : ""}`}>
      <span>
        <span className="messageTime">{time}</span>
        <span className="userBadges">
          {badges.map((badge, i) => (
            <img key={i} src={badge} className="badge" />
          ))}
        </span>
        <span className="messageUsername" style={{ color }}>
          {username}
        </span>
        <span className="spliter">: </span>
        <span
          className="messageText"
          dangerouslySetInnerHTML={{ __html: sanitizedText }}
        />
      </span>
    </div>
  );
}
