// packages/app/vue/src/components/ChatView.vue
<script setup>
import { onMounted, reactive, ref } from "vue";
import ChatMessage from "./ChatMessage.vue";

import { validateToken, getUsers } from "../lib/twitch";
import { parseMessage, parseSystemMessage } from "../lib/parsers";
import getBadges from "../lib/badges";

const props = defineProps({
  channel: String,
});

const badgesList = ref({});

const messages = reactive([]);
let websocket = null;

const user = "justinfan20762";

function isSystemMessage(msg) {
  const parts = msg.split(" ");
  return parts.some((part) => part == ":tmi.twitch.tv" || part == user);
}

function connectChat() {
  websocket = new WebSocket("wss://irc-ws.chat.twitch.tv/");
  websocket.onopen = () => {
    document.getElementById("chatLoader").remove();
    websocket.send("CAP REQ :twitch.tv/tags twitch.tv/commands");
    websocket.send("PASS SCHMOOPIIE");
    websocket.send(`NICK ${user}`);
    websocket.send(`USER ${user} 8 * :${user}`);
    websocket.send("JOIN #" + props.channel);
  };
  websocket.onmessage = (msg) => {
    const data = parseMessage(msg.data, badgesList.value);
    if (
      ![user, "tmi.twitch.tv", `${user}.tmi.twitch.tv`].includes(
        data.fromUser.replace("\r\n", "")
      )
    ) {
      addMessage(data);
    } else {
      const systemMessage = parseSystemMessage(msg.data);

      if (systemMessage.action === "CLEARCHAT") {
        messages.splice(0);
        setTimeout(
          () =>
            addMessage({
              fromUser: "system",
              message: "Chat has been cleaned",
              tags: {
                badges: [
                  "https://static-cdn.jtvnw.net/badges/v1/d97c37bd-a6f5-4c38-8f57-4e4bef88af34/2",
                ],
                emotes: "",
                color: "#ffffff",
                username: "system",
                time: "--:--",
              },
            }),
          100
        );
      } else if (systemMessage.action === "CLEARMSG") {
        const indexToRemove = messages.findIndex(
          (message) => message.tags.id === systemMessage.data.TargetMsgId
        );
        if (indexToRemove > -1) {
          messages.splice(indexToRemove, 1);
        }
      } else if (systemMessage.action === "PING") {
        websocket.send("PONG");
      }
    }
  };
}
function addMessage(message) {
  messages.push(message);
}
async function checkTokenValid() {
  const credentials = localStorage.getItem("botCredentials");
  if (!credentials) return false;

  return await validateToken(credentials);
}
async function getChatBadges(broadcaster_id) {
  badgesList.value = await getBadges(broadcaster_id);
}

onMounted(() => {
  checkTokenValid().then((isValid) => {
    if (!isValid) {
      addMessage({
        fromUser: "system",
        message: "The token is invalid. Some functions will not be available",
        tags: {
          badges: [
            "https://static-cdn.jtvnw.net/badges/v1/d97c37bd-a6f5-4c38-8f57-4e4bef88af34/2",
          ],
          emotes: "",
          color: "#ffffff",
          username: "system",
          time: "--:--",
        },
      });
    }
  });

  getUsers(
    props.channel,
    localStorage.getItem("botCredentials"),
    localStorage.getItem("clientId")
  ).then((json) => getChatBadges(json.data[0].id));
  connectChat();
});
</script>

<template>
  <div id="chat">
    <ChatMessage
      time="--:--"
      id="chatLoader"
      username="system"
      text="Please wait, connection to Twitch chat is in progress!"
      userColor="#ff0000"
      :badges="[
        'https://static-cdn.jtvnw.net/badges/v1/d97c37bd-a6f5-4c38-8f57-4e4bef88af34/2',
      ]"
    />
    <ChatMessage
      v-for="(message, index) in messages"
      :key="index"
      :username="message.fromUser"
      :text="message.message"
      :badges="message.tags.badges"
      :color="message.tags.color"
      :emotes="message.tags.emotes"
      :time="message.time"
      :highlight="message.tags.MsgId == 'highlighted-message'"
      :id="message.tags.id"
    />
  </div>
</template>

<style>
#chat {
  position: absolute;
  right: var(--chatRight);
  left: var(--chatLeft);
  bottom: 12px;
  display: flex;
  flex-direction: column;
  gap: 16px;

  max-width: 800px;
  min-width: 300px;

  overflow-y: hidden;
}
</style>

// packages/app/react/src/components/chat/view/ChatView.tsx
import { useEffect, useRef, useState } from "react";
import { ChatMessage } from "../message/ChatMessage";
import { validateToken, getUsers } from "../../../lib/twitch";
import { parseMessage } from "../../../lib/parsers/message";
import { parseSystemMessage } from "../../../lib/parsers/systemMessage";
import getBadges from "../../../lib/bages";

interface Message {
  fromUser: string;
  message: string;
  time: string;
  tags: {
    badges: (string | undefined)[];
    emotes: string[];
    color: string | null;
    username?: string;
    id?: string;
    MsgId?: string;
  };
}

function ChatView({ channel }: {channel: string}) {
  const [messages, setMessages] = useState<Message[]>([]);
  const [badgesList, setBadgesList] = useState<Record<string, any>>({});
  const websocket = useRef<WebSocket | null>(null);

  const user = "justinfan" + Math.floor(Math.random() * 100000);

  const addMessage = (msg: Message) => {
    setMessages((prev) => [...prev, msg]);
  };

  const connectChat = () => {
    websocket.current = new WebSocket("wss://irc-ws.chat.twitch.tv/");

    websocket.current.onopen = () => {
      if (!websocket.current) return;

      // Подключение к Twitch IRC
      websocket.current.send("CAP REQ :twitch.tv/tags twitch.tv/commands twitch.tv/membership");
      websocket.current.send("PASS SCHMOOPIIE");
      websocket.current.send(`NICK ${user}`);
      websocket.current.send(`USER ${user} 8 * :${user}`);
      websocket.current.send(`JOIN #${channel}`);
    };

    websocket.current.onmessage = (event) => {
      const raw = event.data as string;

      // Ответ на PING
      if (raw.startsWith("PING")) {
        websocket.current?.send(raw.replace("PING", "PONG"));
        return;
      }

      // Парсинг сообщений
      const data = parseMessage(raw, badgesList);

      if (![user, "tmi.twitch.tv", `${user}.tmi.twitch.tv`].includes(data.fromUser)) {
        addMessage(data as Message);
      } else {
        const systemMsg = parseSystemMessage(raw);
        if (systemMsg.action === "CLEARCHAT") {
          setMessages([]);
          setTimeout(() =>
            addMessage({
              fromUser: "system",
              message: "Chat has been cleaned",
              time: "--:--",
              tags: {
                badges: [
                  "https://static-cdn.jtvnw.net/badges/v1/d97c37bd-a6f5-4c38-8f57-4e4bef88af34/2",
                ],
                color: "#ffffff",
                emotes: [],
                username: "system",
              },
            }),
            100
          );
        } else if (systemMsg.action === "CLEARMSG") {
          const targetId = systemMsg.data.TargetMsgId;
          setMessages((prev) => prev.filter((m) => m.tags.id !== targetId));
        }
      }
    };
  };

  const checkTokenValid = async (): Promise<boolean> => {
    const token = localStorage.getItem("botCredentials");
    if (!token) return false;
    return await validateToken(token);
  };

  const loadBadges = async (broadcasterId: string) => {
    const badges = await getBadges(broadcasterId);
    setBadgesList(badges);
  };

  useEffect(() => {
    // Проверка токена и загрузка бейджей
    checkTokenValid().then((isValid) => {
      if (!isValid) {
        addMessage({
          fromUser: "system",
          message: "The token is invalid. Some functions will not be available",
          time: "--:--",
          tags: {
            badges: [
              "https://static-cdn.jtvnw.net/badges/v1/d97c37bd-a6f5-4c38-8f57-4e4bef88af34/2",
            ],
            color: "#ffffff",
            emotes: [],
            username: "system",
          },
        });
      }
    });

    getUsers(channel, localStorage.getItem("botCredentials")!, localStorage.getItem("clientId")!)
      .then((res: any) => loadBadges(res.data[0].id));

    connectChat();

    // Cleanup
    return () => {
      websocket.current?.close();
    };
  }, [channel]);

  return (
    <div id="chat">
      {/* Loader */}
      {messages.length === 0 && (
        <ChatMessage
          time="--:--"
          id="chatLoader"
          username="system"
          text="Please wait, connection to Twitch chat is in progress!"
          color="#ff0000"
          badges={[
            "https://static-cdn.jtvnw.net/badges/v1/d97c37bd-a6f5-4c38-8f57-4e4bef88af34/2",
          ]}
        />
      )}

      {messages.map((msg, idx) => (
        <ChatMessage
          key={idx}
          username={msg.fromUser}
          text={msg.message}
          badges={msg.tags.badges ?? []}
          color={msg.tags.color ?? "#ffffff"}
          emotes={Array.isArray(msg.tags.emotes) ? msg.tags.emotes.join(',') : ''}
          time={msg.time}
          highlight={msg.tags.MsgId === "highlighted-message"}
          id={msg.tags.id}
        />
      ))}
    </div>
  );
};

export default ChatView;
